apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: lab-01
  labels:
    app: nginx
spec:
  containers:
    - name: nginx
      image: nginx:1.25-alpine
      ports:
        - containerPort: 80
      # 실습 편의를 위한 설정
      resources:
        requests:
          cpu: "50m"
          memory: "64Mi"
        limits:
          cpu: "200m"
          memory: "256Mi"
