apiVersion: v1
kind: Pod
metadata:
  name: ed-pod
  namespace: lab-04
spec:
  containers:
    - name: writer
      image: busybox:1.36
      command:
        [
          "sh",
          "-c",
          "echo 'Hello from EmptyDir' > /data/hello.txt && sleep 3600",
        ]
      volumeMounts:
        - mountPath: /data
          name: cache-vol
    - name: reader
      image: busybox:1.36
      command: ["sh", "-c", "sleep 3600"]
      volumeMounts:
        - mountPath: /data
          name: cache-vol
  volumes:
    - name: cache-vol
      emptyDir: {}
